# Copyright (c) 2023 Common Ground Electronics <https://cgnd.dev>
# SPDX-License-Identifier: Apache-2.0

repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v16.0.6
    hooks:
    - id: clang-format
  - repo: https://github.com/cgnd/zephyr-pre-commit-hooks
    rev: v0.1.2
    hooks:
    - id: zephyr-checkpatch
